version: '3.1'

services:
  drupal:
    image: drupal
    ports:
     - "5000:80"
    volumes:
     - drupal-modules:/var/www/html/modules
     - drupal-profiles:/var/www/html/profiles
     - drupal-themes:/var/www/html/themes
     - drupal-sites:/var/www/html/sites
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD_FILE=/run/secrets/sqlpass
    secrets:
     - sqlpass
    volumes:
     - drupal-data:/var/lib/postgressql/data
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:
secrets:
  sqlpass:
    external: true
