# Drupal with PostgreSQL
# Access via "http://http://192.168.99.100:8080"
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: admin
# ADVANCED OPTIONS; Database host: postgres (which is the service name)

version: '3.0'

services:

  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    networks:
      - mynet
    restart: always

  postgres:
    image: postgres:10
    networks:
      - mynet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
    restart: always

networks:
    mynet:
volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    
    
    
#docker swarm join --token SWMTKN-1-521xfqmujyinz6ida87ffofafzmypuvjtt6bhddhyxpz2kaqz8-2snwb15nts8057t91do9jsfdr 192.168.0.60:2377